# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:51
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('departure_address', models.CharField(max_length=150, verbose_name='Departure address')),
                ('departure_dt', models.DateTimeField(default=datetime.datetime.now, verbose_name='Start time')),
                ('arrival_address', models.CharField(max_length=150, verbose_name='Arrival address')),
                ('is_active', models.BooleanField(default=True)),
                ('arrival_city', models.ForeignKey(help_text='Arrival must be related to country selected', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_point', to='cities_light.City', verbose_name='Arrival city')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Cars', verbose_name='Car')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country', verbose_name='Country')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
                ('departure_city', models.ForeignKey(help_text='Departure must be related to country selected', on_delete=django.db.models.deletion.CASCADE, related_name='departure_point', to='cities_light.City', verbose_name='Departure city')),
            ],
            options={
                'verbose_name': 'journey',
                'verbose_name_plural': 'List of journey',
            },
        ),
    ]
