# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journey',
            name='arrival',
            field=models.ForeignKey(help_text='Arrival must be related to country selected', on_delete=django.db.models.deletion.CASCADE, related_name='arrival_point', to='courses.LocationPoint', verbose_name='Arrival'),
        ),
        migrations.AlterField(
            model_name='journey',
            name='departure',
            field=models.ForeignKey(help_text='Departure must be related to country selected', on_delete=django.db.models.deletion.CASCADE, related_name='departure_point', to='courses.LocationPoint', verbose_name='Departure'),
        ),
    ]
