# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 22:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20160527_2206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpoint',
            options={'verbose_name': 'Emplacement', 'verbose_name_plural': 'List of locations'},
        ),
    ]
