# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 12:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('is_reserved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Company cars',
            },
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('slug_name', models.SlugField()),
                ('is_active', models.BooleanField(default=True)),
                ('cities', models.ManyToManyField(blank=True, to='cities_light.City')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.Country')),
            ],
            options={
                'verbose_name': 'A company',
                'verbose_name_plural': 'List of companies',
            },
        ),
        migrations.AddField(
            model_name='cars',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.Companies'),
        ),
        migrations.AddField(
            model_name='cars',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.City'),
        ),
    ]
